export { default as Main } from './main'
export { default as LogIn } from './login'
export { default as SignUp } from './signup'
export { default as GoodsDetail } from './product/[id]'
export { default as GoodsList } from './goodsList'