export { default as Main } from './main'
export { default as Login } from './login'
export { default as Signup } from './signup'
export { default as ProductDetail } from './product/[id]'
export { default as ProductList } from './productList'